### ISSUE TITLE
Remove question mark from "Rotate 360?" and replace checkbox for "Yes" or "No"

### ISSUE THREAD

**Issue by Publicspac3** [rlcustomdesigns/form#7]
Created by: Spinonimus ♆#1257 (886315567194210354)
Date created: 25 July 2022
Link: https://discord.com/channels/376981415633354753/909753930353877052/1001038942914752593

Suggestion: 
Remove question mark from "Rotate 360?" on the form, and replace checkbox for "Yes" or "No"

Images:
![bugreport4](https://user-images.githubusercontent.com/81590651/181728669-f5011952-3708-4ddd-b08c-ae91f91b708d.jpg)
![bugreport3](https://user-images.githubusercontent.com/81590651/181728674-0d7b2df8-640f-4f40-ae2e-b20f6bcac54b.jpg)

**Comment by vikasbhatia** [comment]
Resolved with ed9a3a631be38cbedc06830291a9a5c133a35e4a.
